// a2l_generator.h - Fixed for basic types
#pragma once
#include <fstream>
#include <string>
#include <vector>

class A2LGenerator {
private:
    std::vector<std::string> variables_;
    std::string project_name_;

public:
    A2LGenerator(const std::string& project_name = "FanatecPedals")
        : project_name_(project_name) {
    }

    void add_variable(const std::string& name, const std::string& description, const std::string& type) {
        std::string var_entry = "    /begin CHARACTERISTIC " + name + "\n";
        var_entry += "      \"" + description + "\"\n";
        var_entry += "      VALUE\n";

        // Set default value and range based on type
        if (type == "UBYTE") {
            var_entry += "      0\n";
            var_entry += "      " + name + "\n";
            var_entry += "      UBYTE\n";
            var_entry += "      0 255\n";
        }
        else if (type == "UWORD") {
            var_entry += "      0\n";
            var_entry += "      " + name + "\n";
            var_entry += "      UWORD\n";
            var_entry += "      0 300\n";
        }

        var_entry += "      ECU_ADDRESS 0x0000\n";
        var_entry += "      /begin IF_DATA XCP\n";
        var_entry += "        /begin DAQ_STATIC\n";
        var_entry += "          0\n";
        var_entry += "          1\n";
        var_entry += "          0\n";
        var_entry += "        /end DAQ_STATIC\n";
        var_entry += "      /end IF_DATA\n";
        var_entry += "    /end CHARACTERISTIC\n\n";

        variables_.push_back(var_entry);
    }

    bool generate(const std::string& filename) {
        std::ofstream file(filename);
        if (!file.is_open()) return false;

        file << "/* generated by SimpleXCP Generator */\n";
        file << "ASAP2_VERSION 1 71\n\n";
        file << "/begin PROJECT " << project_name_ << " \"Fanatec Pedal Measurement\"\n\n";
        file << "  /begin MODULE PedalModule \"Pedal Data Module\"\n\n";

        // Simple A2ML section
        file << "    /begin A2ML\n";
        file << "      // Basic XCP protocol definition\n";
        file << "    /end A2ML\n\n";

        // Add variables
        file << "    /* Measurement Variables */\n";
        for (const auto& var : variables_) {
            file << var;
        }

        file << "  /end MODULE\n\n";
        file << "/end PROJECT\n";

        file.close();
        return true;
    }
};